### ISSUE TITLE
https://evercam.com/construction/

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-public-site-2#8]
on the timelapse tab, put the gif in a frame, like a monitor or similar.

**Comment by marcoherbst** [comment]
![image](https://cloud.githubusercontent.com/assets/5648894/17335136/d38c14e8-58d0-11e6-97c1-bff88421f198.png)

**Comment by marcoherbst** [comment]
Then use the same image on the /features page.

You may need the larger original and you may want to have it as a video not gif.

**Comment by affan00** [comment]
it's done.
